In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

from costs import *
from functions import *
from helpers import *
from build_polynomial import *

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH, sub_sample=True)

# Exploratory Data Analysis

Here in this notebook, we will try to explore the data, following wikipedia page and some other web help (that we will listed below) to understand better what represent each feature and how we can use it.

https://en.wikipedia.org/wiki/Exploratory_data_analysis

In [19]:
tX[ range(2) ]

array([[  1.38470000e+02,   5.16550000e+01,   9.78270000e+01,
          2.79800000e+01,   9.10000000e-01,   1.24711000e+02,
          2.66600000e+00,   3.06400000e+00,   4.19280000e+01,
          1.97760000e+02,   1.58200000e+00,   1.39600000e+00,
          2.00000000e-01,   3.26380000e+01,   1.01700000e+00,
          3.81000000e-01,   5.16260000e+01,   2.27300000e+00,
         -2.41400000e+00,   1.68240000e+01,  -2.77000000e-01,
          2.58733000e+02,   2.00000000e+00,   6.74350000e+01,
          2.15000000e+00,   4.44000000e-01,   4.60620000e+01,
          1.24000000e+00,  -2.47500000e+00,   1.13497000e+02],
       [  2.19057000e+02,   7.24610000e+01,   1.24835000e+02,
          5.50600000e+00,  -9.99000000e+02,  -9.99000000e+02,
         -9.99000000e+02,   3.77100000e+00,   4.69360000e+01,
          1.22986000e+02,   1.93200000e+00,  -1.38200000e+00,
         -9.99000000e+02,   2.47590000e+01,  -1.06300000e+00,
          3.32000000e-01,   4.78300000e+01,   1.34700000e+00,
       

In [14]:
def pretty_print(matrix):
    s = [[str(e) for e in row] for row in matrix]
    lens = [max(map(len, col)) for col in zip(*s)]
    fmt = '\t'.join('{{:{}}}'.format(x) for x in lens)
    table = [fmt.format(*row) for row in s]
    print('\n'.join(table))
    
def transpose(matrix):
    return zip(*matrix)

In [30]:
def summarize_data(tX):
    """ get the label and the five number summary of each features """
    # label names
    labels = load_header(DATA_TRAIN_PATH)
    # maximum
    maximums = np.amax(tX, axis=0)
    # minimum
    minimums = np.amin(tX, axis=0)
    # median
    median = np.median(tX, axis = 0)
    # upper quartile
    
    # lower quartile
    
    # transpose matrix and add label
    matrix = transpose([labels, maximums, minimums, median])
    return matrix

a = summarize_data(tX)

pretty_print(a)

std_tx = standardize(tX)
summarize_data(tX)

Id                         	977.515 	-999.0	103.483 
Prediction                 	256.371 	0.011 	48.3055 
DER_mass_MMC               	658.494 	9.463 	73.3785 
DER_mass_transverse_met_lep	585.661 	0.0   	38.0865 
DER_mass_vis               	7.544   	-999.0	-999.0  
DER_pt_h                   	3056.908	-999.0	-999.0  
DER_deltaeta_jet_jet       	15.228  	-999.0	-999.0  
DER_mass_jet_jet           	5.423   	0.256 	2.4935  
DER_prodeta_jet_jet        	257.324 	0.0   	12.175  
DER_deltar_tau_lep         	1279.985	46.227	121.7135
DER_pt_tot                 	9.955   	0.136 	1.291   
DER_sum_pt                 	1.414   	-1.414	-0.4395 
DER_pt_ratio_lep_tau       	1.0     	-999.0	-999.0  
DER_met_phi_centrality     	301.229 	20.001	31.246  
DER_lep_eta_centrality     	2.463   	-2.468	0.0125  
PRI_tau_pt                 	3.141   	-3.141	-0.0595 
PRI_tau_eta                	263.69  	26.005	40.06   
PRI_tau_phi                	2.48    	-2.482	-0.009  
PRI_lep_pt                 	3.141   	-3.141	0.

(array([[ 1.        ,  0.48528033,  0.03965436, ...,  1.54863904,
          1.5407369 ,  0.39818214],
        [ 1.        ,  0.67601018,  0.63344061, ..., -0.64686729,
         -0.64686766, -0.23179611],
        [ 1.        ,  0.3724594 , -0.64151886, ..., -0.64686729,
         -0.64686766, -0.10829837],
        ..., 
        [ 1.        ,  0.49445625, -1.22366112, ..., -0.64686729,
         -0.64686766,  0.23416077],
        [ 1.        ,  0.34254595, -0.11217409, ..., -0.64686729,
         -0.64686766, -0.41106251],
        [ 1.        ,  0.46533331, -1.31829705, ..., -0.64686729,
         -0.64686766, -0.22539659]]),
 array([ -6.65702052e+01,   5.02655292e+01,   8.10068096e+01,
          5.72432294e+01,  -7.03584253e+02,  -5.96237100e+02,
         -7.04529779e+02,   2.37571420e+00,   1.89751598e+01,
          1.57925417e+02,   1.44750460e+00,  -1.58575000e-01,
         -7.04154751e+02,   3.79714208e+01,  -7.52940000e-03,
         -7.32000000e-05,   4.63404222e+01,  -1.99772000e-02,


In [14]:

print(reader)

In [26]:
labels = load_header(DATA_TRAIN_PATH)
print(labels)

['Id' 'Prediction' 'DER_mass_MMC' 'DER_mass_transverse_met_lep'
 'DER_mass_vis' 'DER_pt_h' 'DER_deltaeta_jet_jet' 'DER_mass_jet_jet'
 'DER_prodeta_jet_jet' 'DER_deltar_tau_lep' 'DER_pt_tot' 'DER_sum_pt'
 'DER_pt_ratio_lep_tau' 'DER_met_phi_centrality' 'DER_lep_eta_centrality'
 'PRI_tau_pt' 'PRI_tau_eta' 'PRI_tau_phi' 'PRI_lep_pt' 'PRI_lep_eta'
 'PRI_lep_phi' 'PRI_met' 'PRI_met_phi' 'PRI_met_sumet' 'PRI_jet_num'
 'PRI_jet_leading_pt' 'PRI_jet_leading_eta' 'PRI_jet_leading_phi'
 'PRI_jet_subleading_pt' 'PRI_jet_subleading_eta' 'PRI_jet_subleading_phi'
 'PRI_jet_all_pt']
