In [3]:
import numpy as np

In [4]:
y = np.array([1, 2, 3, 4])

print("y = ", y)
z = np.array([[5], [6], [7], [8]])
print("z = ", z)
print("y @ z = ", y @ z)
print("z @ y throw an error!")
print(z @ y)

y =  [1 2 3 4]
z =  [[5]
 [6]
 [7]
 [8]]
y @ z =  [70]
z @ y throw an error!


ValueError: shapes (4,1) and (4,) not aligned: 1 (dim 1) != 4 (dim 0)

In [5]:
y = np.array([1, 2, 3, 4])
z = np.array([[5], [6], [7], [8]])

# why that ? because if we look at the shape of y, 
#it's a vector, not a 2D matrix with one row, as we would like to have
print("y shape = ", y.shape)
# then if you transpose it... it stay a vector!
print("y.T shape = ", y.T.shape)
# so if you want to make it a matrix, you need to add it a new axis with dimension 1
y = y[np.newaxis, :]
# now look at the new y and its shape
print("new y = ", y)
# we see that it contains new 2 brackets instead of one, meaning that we add the whished dimension
print("new y shape = ", y.shape)
print("new y.T shape = ", y.T.shape)

# then we can do all the multiplication we want:
print("y shape = ", y.shape)
print("z shape = ", z.shape)
print("y @ z = ", y @ z)
print("z @ y = ", z @ y)

y shape =  (4,)
y.T shape =  (4,)
new y =  [[1 2 3 4]]
new y shape =  (1, 4)
new y.T shape =  (4, 1)
y shape =  (1, 4)
z shape =  (4, 1)
y @ z =  [[70]]
z @ y =  [[ 5 10 15 20]
 [ 6 12 18 24]
 [ 7 14 21 28]
 [ 8 16 24 32]]


In [6]:
# the trick comes from the fact that you can multiply a vector with a matrix, so you think everything is ok, 
# but actually... it's not