In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [5]:
A=np.array([[400, -201], [-800, 401]])
A

array([[ 400, -201],
       [-800,  401]])

In [11]:
Ainv = np.linalg.inv(A)
Ainv

array([[-1.0025, -0.5025],
       [-2.    , -1.    ]])

In [10]:
401/400

1.0025

In [9]:
201/400

0.5025

In [12]:
y = np.array([200, -200])
np.dot(Ainv, y)

array([-100., -200.])

In [14]:
np.dot(A, np.array([-100., -200.]))

array([ 200., -200.])

In [17]:
A2=np.array([[401, -201], [-800, 401]])
A2

array([[ 401, -201],
       [-800,  401]])

In [19]:
A2inv = np.linalg.inv(A2)
A2inv

array([[ 401.,  201.],
       [ 800.,  401.]])

In [20]:
y = np.array([200, -200])
np.dot(A2inv, y)

array([ 40000.00000004,  79800.00000007])

In [21]:
np.linalg.cond(A)

2503.0046004809424

In [22]:
np.linalg.cond(A2)

1002003.0000613326

We can try with a linear matrix to see what a normal cond-number looks like: for example the same as first (-100, -200) but with second number different

400 -201   =  200
37  -200   =  -23'700

In [24]:
A3 = np.array([[400, -201], [37, -200]])
np.linalg.cond(A3)

2.9983461505949478

Then if we now calculate the weights of this matrix and a little different one, with same y's, let's see what happen

In [25]:
A4 = np.array([[401, -201], [37, -200]])
A3inv = np.linalg.inv(A3)
A4inv = np.linalg.inv(A4)

print('w1 w2 for A3', np.dot(A3, y))
print('w1 w2 for A4', np.dot(A4, y))

w1 w2 for A3 [120200  47400]
w1 w2 for A4 [120400  47400]


As we can see, at the opposite of the first one, this time a little difference doesn't change almost anything !